### ISSUE TITLE
where is the source code for su2_torch?

### ISSUE THREAD

**Issue by juntang-zhuang** [locuslab/cfd-gcn#1]
Hi, thanks for your work. I wonder where is the code for su2_torch? I could not import it as a module.

**Comment by filipeabperes** [comment]
Hi, sorry but I have still to update the repository to add the ability and instructions for running from source. For now you can run experiments using the Dockerfile.

The source code for su2_torch is currently in a branch in the SU2 repository, but is not up to date with the most current SU2 version. If you want to check it out, you can check out the repository/branch referenced [here](https://github.com/locuslab/cfd-gcn/blob/55f28175ccf825b2850f6e8db6b81c048a521359/Dockerfile#L39), in the `SU2_PY/su2torch` directory. You can also build the docker image and check inside `/SU2/SU2_PY/su2torch` in the docker container.

**Comment by juntang-zhuang** [comment]
Thanks a lot for your reply.
