### ISSUE TITLE
couldn't find su2torch interface file. 

### ISSUE THREAD

**Issue by kyawlin** [locuslab/cfd-gcn#2]

**Comment by filipeabperes** [comment]
can you explain this issue in more detail?

**Comment by kyawlin** [comment]
could you tell me where is su2torch.py? 
Thanks

**Comment by filipeabperes** [comment]
If you look at the [line here](https://github.com/locuslab/cfd-gcn/blob/b4690418254941b6627b2340318f86a31b854bae/Dockerfile#L39) you'll see a git clone from a specific branch of the SU2 repository. The SU2 files are there, as they need to work in conjunction with SU2.

**Comment by kyawlin** [comment]
Thanks. I overlooked.
