### ISSUE TITLE
Math Questions: About the differentiation with respect to nodal coordinates

### ISSUE THREAD

**Issue by junpenggao233** [locuslab/cfd-gcn#4]
Hi, Thank you for your nice work.

I have some questions about the differentiation with respect to nodal coordinates.

It seems that it does not need to calculate the gradients of coordinates on the boundaries (exterior and interior), otherwise, the problem was changed. I found there were shape derivatives of the whole domain (view it as a PDE-constraint optimization problem) and someone also directly calculated nodal sensitivities directly. I am confused about these.  If I view it as a PDE-constraint optimization problem and calculate the shape derivatives with all mesh coordinates, could it replace the sensitivity of the inner mesh coordinates?

I am a little difficult to read the parts of "SU2 differentiable layer", do you mind giving me some hints about these two concepts, and which one do you(or SU2) adopt?

**Comment by filipeabperes** [comment]
Hi, I'm not sure I understand completely your question. But in the experiments reported in the paper we do not use the gradients at the boundary nodes, these are kept fixed, as you can see here: https://github.com/locuslab/cfd-gcn/blob/7d988368cfae494bda8e80d408352cba3b450016/main.py#L162

**Comment by junpenggao233** [comment]
Thank you for your response. It is not exactly what I mean and I am sorry that I do not express my ideas clearly.  For example, there is one paper _Anisotropic mesh adaption based on a posteriori estimates and optimisation of node positions_ derives the explicit formula that the derivative of a discrete numerical scheme with respect to node coordinates. 

There is also some work concerning shape optimization, which seems to view the problems as a PDE-constrained problem, and we get "shape derivative". I am just curious about whether they are equal to each other mathematically, and if we fix the boundary points, to get the gradient information, do we need to add these constraints (fixed boundary mesh constraints) to the PDE-constrained problems? If we do not do this, does it shows on the true gradient information?
